### ISSUE TITLE
Dashboard crashed

### ISSUE THREAD

**Issue by mulkieran** [packit/dashboard#322] opened 2023-08-22 17:04 UTC
Entering URL https://dashboard.packit.dev/projects/github.com/stratis-storage/stratis-cli in my browser's field for URLs causes this.

**Comment by mulkieran** [comment] 2023-08-22 17:05
w/ Python error: ```TypeError: s.map is not a function```

**Comment by lbarcziova** [comment] 2023-08-23 06:24
hi! Thanks for reporting this. 

It looks like this is similar as #319 and caused by packit/packit-service#2153

**Comment by lbarcziova** [comment] 2023-09-05 06:23
The fix is now in production, closing.

**Closed by lbarcziova** 2023-09-05 06:23 UTC
Labels: kind/bug, area/user-experience, complexity/single-task, gain/low, impact/high
