### ISSUE TITLE
Crash with TypeError: e.trigger.builds is undefined

### ISSUE THREAD

**Issue by danmyway** [packit/dashboard#319] opened 2023-08-15 15:39 UTC
Reproducer:
Access https://dashboard.packit.dev/projects/github.com/oamg/convert2rhel and click Load more.

Error message:
TypeError: e.trigger.builds is undefined

**Comment by lbarcziova** [comment] 2023-08-24 11:29
Thanks for reporting! The cause of this is https://github.com/packit/packit-service/issues/2153 so the progress will be tracked there.

**Comment by mfocko** [comment] 2023-09-04 17:39
Can we close as the root cause has been resolved?

**Comment by mfocko** [comment] 2023-09-04 19:01
> What do you mean?

OH! it's the `s.map` from the other issue you just linked

**Comment by lbarcziova** [comment] 2023-09-05 06:24
The fix is now in production, closing.

**Closed** 2023-09-05 06:25 UTC
Labels: kind/bug, area/user-experience, complexity/single-task, gain/low, impact/high
